let all=[], filtered=[], chart;
const $=id=>document.getElementById(id), norm=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const labels={"9_ano":"9º ano","3_em":"3ª série EM"};
const state=JSON.parse(localStorage.getItem('saebFilters')||'{}');
for(const id of ['search','stage','sort']) if(state[id]) $(id).value=state[id];
const avg=(d,k)=>d.reduce((s,x)=>s+x[k],0)/d.length;
function save(){localStorage.setItem('saebFilters',JSON.stringify(Object.fromEntries(['search','stage','sort'].map(id=>[id,$(id).value]))));}
function render(){const term=norm($('search').value); filtered=all.filter(x=>($('stage').value==='todos'||x.etapa===$('stage').value)&&norm(x.nome).split(' ').some(w=>w.includes(term)||term.includes(w))); const by=$('sort').value;filtered.sort((a,b)=>by==='nome'?a.nome.localeCompare(b.nome):b[by==='lp'?'media_lp':'media_mat']-a[by==='lp'?'media_lp':'media_mat']);save(); $('total').textContent=filtered.length; $('lp').textContent=filtered.length?avg(filtered,'media_lp').toFixed(1):'—';$('mat').textContent=filtered.length?avg(filtered,'media_mat').toFixed(1):'—';const best=filtered[0];$('top').textContent=best?best.nome.split(' ').slice(0,2).join(' '):'—';$('insight').textContent=best?`${best.nome} lidera este recorte com média composta de ${((best.media_lp+best.media_mat)/2).toFixed(1)} pontos. A média de Matemática está ${(avg(filtered,'media_mat')-avg(filtered,'media_lp')).toFixed(1)} ponto(s) em relação à de Língua Portuguesa.`:'Nenhum registro atende aos filtros.'; $('rows').innerHTML=filtered.map(x=>`<tr><td class="font-medium">${x.nome}<small class="block text-slate-500">${x.municipio}</small></td><td>${labels[x.etapa]}</td><td>${x.media_lp.toFixed(2)}</td><td>${x.media_mat.toFixed(2)}</td><td>${x.inse}</td><td><button data-id="${x.id}" class="use text-indigo-600 font-semibold">Simular</button></td></tr>`).join(''); draw();}
function draw(){const data=filtered.slice(0,12); if(chart)chart.destroy();chart=new Chart($('ranking'),{type:'bar',data:{labels:data.map(x=>x.nome.split(' ').slice(0,2).join(' ')),datasets:[{label:'Língua Portuguesa',data:data.map(x=>x.media_lp),backgroundColor:'#4f46e5'},{label:'Matemática',data:data.map(x=>x.media_mat),backgroundColor:'#0ea5e9'}]},options:{responsive:true,maintainAspectRatio:false,scales:{y:{min:200}},plugins:{legend:{position:'bottom'}}}})}
function school(){return all.find(x=>x.id===+$('school').value)}
function rates(){const stage=$('simstage').value, years=stage==='9_ano'?['6º','7º','8º','9º']:['1ª','2ª','3ª'];$('rates').innerHTML=years.map((x,i)=>`<label class="text-xs">${x} ano<input class="rate input mt-1" type="number" min="0" max="100" step=".1" value="95"></label>`).join('')}
function sim(){const x=school();if(!x)return;const stage=$('simstage').value;const same=all.find(y=>y.nome.replace(/ \([^)]*\)$/,'')===x.nome.replace(/ \([^)]*\)$/,'')&&y.etapa===stage)||x;const lim=stage==='9_ano'?{lp:[100,400],mat:[100,400]}:{lp:[117,451],mat:[111,467]};const nlp=Math.max(0,Math.min(10,(same.media_lp-lim.lp[0])/(lim.lp[1]-lim.lp[0])*10)),nmat=Math.max(0,Math.min(10,(same.media_mat-lim.mat[0])/(lim.mat[1]-lim.mat[0])*10));$('scores').textContent=`Proficiências: LP ${same.media_lp.toFixed(2)} · MAT ${same.media_mat.toFixed(2)}. Nota padronizada N: ${((nlp+nmat)/2).toFixed(2)}.`;return (nlp+nmat)/2}
async function init(){all=await fetch('./dados/escolas.json').then(r=>r.json());$('school').innerHTML='<option value="">Selecione uma escola</option>'+all.map(x=>`<option value="${x.id}">${x.nome} · ${labels[x.etapa]}</option>`).join('');rates();render();}
['search','stage','sort'].forEach(id=>$(id).addEventListener(id==='search'?'input':'change',render));$('school').addEventListener('change',sim);$('simstage').addEventListener('change',()=>{rates();sim()});$('rows').addEventListener('click',e=>{if(e.target.classList.contains('use')){$('school').value=e.target.dataset.id;$('simstage').value=all.find(x=>x.id==e.target.dataset.id).etapa;rates();sim();location.hash='school'}});$('calculate').addEventListener('click',()=>{const n=sim();if(n===undefined)return;const p=[...document.querySelectorAll('.rate')].reduce((s,x)=>s+(+x.value||0),0)/document.querySelectorAll('.rate').length/100;$('ideb').textContent=`IDEB simulado: ${(n*p).toFixed(2)} (N ${n.toFixed(2)} × P ${p.toFixed(3)})`;});$('csv').addEventListener('click',()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([[['Escola','Etapa','Português','Matemática'].join(';'),...filtered.map(x=>[x.nome,labels[x.etapa],x.media_lp,x.media_mat].join(';'))].join('\n')],{type:'text/csv'}));a.download='saeb-filtrado.csv';a.click()});$('print').onclick=()=>print();init();
